### ISSUE TITLE
Compilation issue with Elixir 1.3.1 and Distillery 1.3.5

### ISSUE THREAD

**Issue by farao** [bitwalker/distillery#260]
I just upgraded to distillery 1.3.5 and used it with Elixir 1.4.2 and 1.3.1. While on Elixir 1.4.2 everything was fine, it didn't compile with 1.3.1.

### Steps to reproduce

mix deps.clean
mix deps.compile

### Verbose Logs

==> distillery
Compiling 18 files (.ex)

== Compilation error on file lib/mix/lib/releases/assembler.ex ==
** (CompileError) lib/mix/lib/releases/assembler.ex:558: cannot invoke local when/2 inside match, called as: {:error, error_info, _end_loc} when :erlang.is_tuple(error_info)
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
    (stdlib) lists.erl:1354: :lists.mapfoldl/3

**Comment by bitwalker** [comment]
I pushed a fix for this just now, should be released soon.

**Comment by bitwalker** [comment]
Fixed in 1.4.0
